blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/daneel-ai/extension/discussions
    about: Ask questions, share ideas, or connect with other users
